Backport : Global Audit View for vulnerabilities
DependencyTrack/hyades-apiserver pull request #723
Opened 2024-06-13 14:00 UTC by sahibamittal

### Description

This PR introduces introduces new API endpoints in the FindingResource of the backend. These two new endpoints filter every finding by ACLs and other optional filters and then returns them , either by occurrence of vulnerability or grouped by vulnerability.

### Addressed Issue

Backport change https://github.com/DependencyTrack/hyades/issues/1190

### Checklist

- [ ] I have read and understand the [contributing guidelines](../CONTRIBUTING.md#pull-requests)
- [ ] This PR fixes a defect, and I have provided tests to verify that the fix is effective
- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended
- [ ] This PR introduces changes to the database model, and I have updated the [migration changelog](https://github.com/DependencyTrack/hyades-apiserver/tree/main/src/main/resources/migration) accordingly
- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/hyades/tree/main/docs) accordingly

2024-06-13 15:07 UTC, sahibamittal commented
Tested with frontend https://github.com/DependencyTrack/hyades-frontend/tree/rebase-v4.11.3

<img width="1512" alt="Screenshot 2024-06-13 at 16 06 43" src="https://github.com/DependencyTrack/hyades-apiserver/assets/5709882/8e6be4cb-8f45-4051-bdf1-803c2ad06fa1">

2024-06-14 11:07 UTC, nscuro requested changes

2024-06-14 11:07 UTC, nscuro commented on src/main/java/org/dependencytrack/model/GroupedFinding.java
> +                LEFT JOIN "PROJECT_ACCESS_TEAMS" ON ("PROJECT"."ID" = "PROJECT_ACCESS_TEAMS"."PROJECT_ID")
I just noticed that I labeled https://github.com/DependencyTrack/dependency-track/pull/3701 as `NA` in the porting issue. But it contains the corrected query. :sweat_smile: Please have a look at that.

2024-06-14 13:54 UTC, nscuro commented on src/main/java/org/dependencytrack/persistence/FindingsSearchQueryManager.java
> +                )""".formatted(teamIds));
`teamIds` should be passed as query parameters:

```suggestion
                     AND "PROJECT_ACCESS_TEAMS"."TEAM_ID" = ANY(:teamIds)
                )""");
        params.put("teamIds", teamIds);
```

2024-06-16 17:24 UTC, nscuro approved these changes

2024-06-16 17:24 UTC, merged